name: Tests

on: [push]

jobs:
  shader-tests:
    runs-on: ubuntu-latest
    env:
      IMGUR_TOKEN: ${{ secrets.IMGUR_TOKEN }}
    steps:
    - uses: actions/checkout@master
    - name: Install dependencies
      run: sudo apt-get install -y libmagickwand-dev libosmesa-dev imagemagick
    - name: Run tests
      run: make
