name: Tests

on: [push]

jobs:
  shader-tests:
    runs-on: ubuntu-latest

    container:
      image: ghcr.io/${{ github.repository_owner }}/offscreen-rendering-ci-image:latest

    env:
      IMGUR_TOKEN: ${{ secrets.IMGUR_TOKEN }}
    steps:
    - uses: actions/checkout@master
    - name: Run tests
      run: make
